### ISSUE TITLE
run_epoch leads to float division by zero

### ISSUE THREAD

**Issue by zhichaoxu-shufe** [ldery/Bosai#1]
I am trying to run your code and encounter this error in `lib/scoring_model.py`

in the `run_epoch` function, `n_batches` is zero and leads to float division by zero error in `running_loss_avg /= n_batches`

**Comment by ldery** [comment]
Thanks for the heads up ! 
What hyper-parameter configuration are you using btw. In general this should not be happening unless you're setting `--masks_per_iter` to be very small -- like < 5

**Comment by zhichaoxu-shufe** [comment]
thanks for your prompt reply, changing to a larger value turns to be bug free.

I do have a minor suggestion, it seems right now each time you call the `evaluate` function, it tokenizes the dataset which takes a non-trivial amount of time. 

I modified your code by just pre-tokenize the dataset and save as `.pt` format and can be directly loaded by `torch.load` function, and each load takes ~0.2 seconds with my hardware

**Comment by ldery** [comment]
Ah thanks ! Will remember to make the change in the final updated version. 
Keep me posted how using this repo goes -- excited to see what people do with it
